/**:
    ros__parameters:

        general:
            grab_frame_rate: 30 # ZED SDK internal grabbing rate
            pub_frame_rate: 20.0 # frequency of publishing of visual images and depth images

        depth:
            depth_mode: "NONE" # Matches the ZED SDK setting: 'NONE', 'PERFORMANCE', 'QUALITY', 'ULTRA', 'NEURAL', 'NEURAL_PLUS' - Note: if 'NONE' all the modules that requires depth extraction are disabled by default (Pos. Tracking, Obj. Detection, Mapping, ...)
            depth_stabilization: 1 # Forces positional tracking to start if major than 0 - Range: [0,100]
            openni_depth_mode: true # 'false': 32bit float [meters], 'true': 16bit unsigned int [millimeters]